blank_issues_enabled: false
contact_links:
  - name: Fragen & Ideen
    url: https://github.com/Knick1301/Kontinuierliche-Kreisel-Kaempfe/discussions
    about: Allgemeine Fragen, Ideen und Diskussionen bitte in den Discussions
